### PR TITLE
Add block-based portfolio ("Nwaneri") theme

### PR DESCRIPTION
**Pull request by jffng**
**Description**
This is a pull request that adds a new block-based theme that was designed by @melchoyce.  

[Demo](https://nwaneri.mystagingwebsite.com/)

Screen Shot 2020-01-28 at 11 58 48 AM

This was also an exercise in identifying how Gutenberg / core blocks could be improved and extended to express robust and compelling designs.  Those ideas and issues are documented in #1.  

**How to Test**
Visit the [demo site](https://nwaneri.mystagingwebsite.com/), take note of any issues you find, and add them as feedback to this PR. 

If you wish to test the theme yourself: 
- Install Gutenberg 7.3 and activate the Full Site Editing theme experiment
- Install and activate the theme
- Import the site content
- Switch the home page settings via the Customizer

**Known Issues / To-Do**
- [ ] Add editor styles
- [ ] Add remaining core block styles
- [ ] Add templates for handling tag, archive, 404 pages
- [ ] Add starter content
- [x] Fix hero styles to be consistent across viewports and make sense with the controls the block editor affords
- [x] Add logic to nav to close on 'Esc' and clicking outside the nav area.

### CODE REVIEW

**Comment by melchoyce** [comment]
By default, the latest posts block should be:

3 col item / 1 col space / 3 col item / 3 col space

Or:

30% 10% 30% 30%

image

I'm cool with fudging the numbers (especially since they should all be relative anyway) but I want to make sure the line length doesn't get too long on each post excerpt. We'll need to max the whole grid out at some point — maybe 1580?  Where at that width or wider, the grid stays centered on the page, and the side spacing grows. 

This little guy would still be docked to the bottom left:

image

I think once you increase the number of columns in the latest posts block to 3, it could be:

3 col item / 3 col item / 3 col item / 1 col space

image

After that, columns can be propionate within the grid.

So, let's say:

1 Column of Latest Posts: 3col / 7space
2 Columns of Latest Posts: 3col / 1space / 3col / 3space
3 Columns of Latest Posts: 3col / 3col / 3col / 1space
4+ Columns of Latest Posts: Just divide the max grid by the # of columns

Does this make sense? Am I overcomplicating?

**Comment by melchoyce** [comment]
This line-height should be 1.4:

image

With ~30px of space between the title and tagline:

image

**Comment by melchoyce** [comment]
Clicking or tapping outside of the open navigation menu, or pressing `esc`, should close it.

**Comment by jffng** [comment]
@melchoyce thanks for the review!

> 1 Column of Latest Posts: 5col / 5space
> 2 Columns of Latest Posts: 3col / 1space / 3col / 3space
> 3 Columns of Latest Posts: 3col / 3col / 3col / 1space
> 4+ Columns of Latest Posts: Just divide the max grid by the # of columns

I get what you mean. I may have to approximate the column widths as I want to balance the amount of custom CSS with the current way the Latest Posts block applies styles based on the number of columns a user selects in Gutenberg.

Everything else is straightforward to address.

**Comment by melchoyce** [comment]
Approximation is totally fine. Thanks!!

**Comment by jffng** [comment]
@melchoyce I'm using a block style variation on the media text block for the hero image treatment. When the media appears on the left, should the blobs be flipped or remain on the left?

Screen Shot 2020-02-20 at 1 07 51 PM

**Comment by melchoyce** [comment]
Could you test flipped?

**Comment by jffng** [comment]
Sure thing, here's a more considered side-by-side:

Screen Shot 2020-02-20 at 2 40 52 PM


Screen Shot 2020-02-20 at 2 38 23 PM

I could go either way.

**Comment by melchoyce** [comment]
I do like the shapes framing the text, so let's go with flipping the shapes.

**Comment by kjellr** [comment]
I'm going to close this one for now since we're moving this repo over to [automattic/themes](https://github.com/automattic/themes). I'll leave the branch intact in case we need to take a look at it in the future.

**Pull request closed without merging**
