### PR TITLE
Varya: Refine the post comments

### PR DESCRIPTION
**Pull request by jffng**
This PR updates the existing post comments section to be more in line with design comps (#49). 

_Before_ 

Screen Shot 2020-04-07 at 4 20 11 PM

_After_

Screen Shot 2020-04-07 at 4 19 15 PM
Screen Shot 2020-04-07 at 4 18 58 PM

### CODE REVIEW

**Comment by allancole** [comment]
Couple more small things I noticed :-)

Let’s make the form line-hieght match the body line-height. This looks too tight: 
image

“Cancel Reply” seems like its floating here. Maybe it should be centered or bottom-aligned with the “Leave a Comment” text? cc: @kjellr for design direction
image

**Comment by jffng** [comment]
@allancole @kjellr Thanks for checking this out! I took another pass and made the following changes: 

- Logged out state
- Alignment of the author information
- Line height and padding of the form fields
- Slight adjustment of the "Cancel Reply" state

Screen Shot 2020-04-08 at 3 26 41 PM

I also added a bottom border, to avoid long lists of comments bleeding together:

Screen Shot 2020-04-08 at 3 27 55 PM

**Comment by allancole** [comment]
I say LGTM! 👍

**Comment by kjellr** [comment]
Made a small update to the borders:

- Removed the topmost border, so there's no border between the "Comments" header and the first comment.
- Used a lighter color for the border, so it's not as bold. 

Screen Shot 2020-04-09 at 2 51 21 PM

@allancole I used `--global--color-border-dark` here, and I also lightened that color in `_config.scss`. What are all these `light`/`dark` variations used for? The color I picked is also used in `--global--color-background-light`, and I'm not sure if that's a problem.

**Comment by allancole** [comment]
> I used --global--color-border-dark here, and I also lightened that color in _config.scss. What are all these light/dark variations used for? The color I picked is also used in --global--color-background-light, and I'm not sure if that's a problem.

Yeah, I just took another look at those border variables and they’re not as intuitive as they probably should be. 

In the same way that `--global--color-foreground` has a `-light` and `-dark` variation, I figured border colors could benefit from variations too, but so far it’s been kind of a rare thing to use. They’ve been in the system for a while, but I don’t think I’ve ever actually changed them. 

I think it’s worth removing the variations and just keeping the one border-color. I’ll make an issue for it 👍

**Comment by kjellr** [comment]
> I think it’s worth removing the variations and just keeping the one border-color. I’ll make an issue for it

Cool, sounds good. In the meantime, I'll merge this in. 👍

**Pull request merged**
