### PR TITLE
Varya: Change primary color from red to green

### PR DESCRIPTION
**Pull request by kjellr**
This has been simmering for a while, but before I create a screenshot for #133, I figured we'd make a final call. The current rose color has been ok, but it feels a little dreary. In keeping with the botany/plants theme, I'd love to switch to a green color. The one in here was explored previously in comps, and I think works pretty well. 

Current|Proposed
---|---
Dark Red|Teal

cc @melchoyce, @allancole, @jffng

### CODE REVIEW

**Comment by kjellr** [comment]
Here's a broader spectrum of things that were considered. The current color is on the left, and this new green one is second from the right: 

Screen Shot 2020-05-20 at 10 05 21 AM

**Comment by kjellr** [comment]
Excellent, thank you. I've updated the screenshot, so this PR will now also fix #133.

**Comment by jffng** [comment]
Should the text-selection color be updated also? 

Screen Shot 2020-05-20 at 3 09 31 PM

**Comment by kjellr** [comment]
Ah, right. That should be updated too. I wish we could automate that somehow. 🤔

**Pull request merged**
