### PR TITLE
Varya: Add initial readme.txt to pass TRT requirements.

### PR DESCRIPTION
**Pull request by allancole**
This is a first pass at adding a readme.txt file to pass the TRT requirements. I mostly just borrowed copy from the markdown version of this file, but let’s discuss what should actually go in here below. 

Fixes: #74

### CODE REVIEW

**Comment by kjellr** [comment]
I pushed a few small updates — mostly to the description and credit lines. I also synced these up with the `style.css` file. I think this is probably good to go. 

Quick question: for the copyright, do we need to credit anything specifically to Twenty Nineteen or Twenty Twenty?

**Comment by allancole** [comment]
> do we need to credit anything specifically to Twenty Nineteen or Twenty Twenty?

Hmmm. I wanna say yes to Twenty Nineteen, but for Twenty Twenty, I’m not so sure. I’m sure there’s something in here from Twenty Twenty but I don’t know what exactly.

**Comment by kjellr** [comment]
There's a function from Twenty Twenty in the colors PR. I'll at least call that out. Will submit a few other changes here later today. 👍

**Comment by kjellr** [comment]
Ok, I've added some new updates to the license. Primarily, I've: 

- Noted that this is derivative of Twenty Nineteen. Based on the amount of little Twenty Nineteen code bits in here, I think that's true, right @allancole? 
- I've also noted that one of the functions used in #113 is straight from Twenty Twenty, since I think that's going to make it in. 

This should be good to go. 👍

**Comment by allancole** [comment]
> this is derivative of Twenty Nineteen. Based on the amount of little Twenty Nineteen code bits in here, I think that's true, right @allancole?

Yeah, I’d say that’s pretty accurate and that this PR is good to go. 

LGTM! 👍

**Pull request merged**
